#/idcheck.ajax=auth.command.IDCheckHandler


/store/mapSearch.ajax=mvc.command.store.MapSearchHandler




/join/emailCheck.ajax=mvc.command.join.EmailCheckHandler
/join/nicknameCheck.ajax=mvc.command.join.NickNameCheckHandler
/join/idCheck.ajax=mvc.command.join.IdCheckHandler
/join/phoneSendCode.ajax=mvc.command.join.PhoneSendCodeHandler
/join/phoneVerifyCode.ajax=mvc.command.join.PhoneVerifyCodeHandler