# requestURI=CommandHandler Mapping
# /board/list.do=mvc.command.ListHandler
/menu/list.do=mvc.command.menu.ListHandler
/views/play/event/list.do=mvc.command.event.ListHandler
/views/play/event/view.do=mvc.command.event.ViewHandler
/views/play/plaza/list.do=mvc.command.plaza.ListHandler
/views/play/plaza/view.do=mvc.command.plaza.ViewHandler
/views/play/plaza/consulting.do=mvc.command.plaza.ConsultingHandler
/api/store-address.do=mvc.command.api.StoreAddressProxyHandler
/views/play/plaza/new.do=mvc.command.plaza.NewHandler
/views/play/plaza/collabo.do=mvc.command.plaza.CollaboHandler
/views/play/recipe/list.do=mvc.command.recipe.ListHandler
/views/play/recipe/view.do=mvc.command.recipe.ViewHandler
/views/play/myflavor/list.do=mvc.command.myflavor.ListHandler
/views/play/myflavor/register.do=mvc.command.myflavor.RegisterHandler
/views/play/myflavor/image.do=mvc.command.myflavor.MyFlavorImageHandler