# requestURI=CommandHandler Mapping
/index.do=mvc.command.IndexHandler
#/board/list.do=mvc.command.ListHandler
#/menu/list.do=mvc.command.menu.ListHandler
/notice/list.do=mvc.command.notice.NoticeListHandler
/notice/view.do=mvc.command.notice.NoticeViewHandler
/press/list.do=mvc.command.press.PressListHandler
/press/view.do=mvc.command.press.PressViewHandler
/faq/list.do=mvc.command.faq.FaqListHandler
/search/list.do=mvc.command.search.SearchListHandler
/customer/list.do=mvc.command.customer.CustomerListHandler
/search/board.do=mvc.command.search.BoardSearchHandler
/inquiry/create.do=mvc.command.inquiry.InquiryCreateHandler
/fairtrade/list.do=mvc.command.fairtrade.FairTradeListHandler
/fairtrade/view.do=mvc.command.fairtrade.FairTradeViewHandler






/menu/list.do=mvc.command.menu.ListHandler

/story/be-better.do=mvc.command.story.CampaignInfoHandler
/story/history.do=mvc.command.story.HistoryListHandler
/story/story.do=mvc.command.story.StoryListHandler
/login/login.do=mvc.command.login.LoginHandler
/login/logout.do=mvc.command.login.LogoutHandler
/join/join.do=mvc.command.join.JoinHandler
/login/findId.do=mvc.command.login.FindIdHandler
/login/findIdPhone.do=mvc.command.login.FindIdPhoneHandler
/login/findIdEmail.do=mvc.command.login.FindIdEmailHandler
/login/pwdResetRequest.do=mvc.command.login.PwdResetRequestHandler
/join/idCheck.do=mvc.command.join.IdCheckHandler
/join/nicknameCheck.do=mvc.command.join.NickNameCheckHandler
/join/emailCheck.do=mvc.command.join.EmailCheckHandler
/join/phoneSendCode.do=mvc.command.join.PhoneSendCodeHandler
/join/phoneVerifyCode.do=mvc.command.join.PhoneVerifyCodeHandler
/mypage/mypage.do=mvc.command.mypage.MyPageViewHandler
/mypage/profileEditForm.do=mvc.command.mypage.ProfileEditFormHandler
/mypage/profileEditSubmit.do=mvc.command.mypage.ProfileEditSubmitHandler
/mypage/nicknameCheck.do=mvc.command.mypage.NickNameCheckHandler
/mypage/emailCheck.do=mvc.command.mypage.EmailCheckHandler
/mypage/phoneSendCode.do=mvc.command.mypage.PhoneSendCodeHandler
/mypage/phoneVerifyCode.do=mvc.command.mypage.PhoneVerifyCodeHandler
#/mypage/pwdChange.do=mvc.command.mypage.PwdChangeHandler

/menu/view.do=mvc.command.menu.ViewHandler
/menu/fom.do=mvc.command.menu.FomHandler
/brapp/brapp.do=mvc.command.brapp.BrappHandler
/store/flavor.do=mvc.command.store.FlavorHandler
/store/workshop.do=mvc.command.store.WorkShopHandler
/store/delivary.do=mvc.command.store.DelivaryHandler
/store/catering.do=mvc.command.store.CateringHandler
/store/map.do=mvc.command.store.MapHandler
/information-center/consulting/br.do=mvc.command.consulting.BrHandler
/information-center/consulting/condition.do=mvc.command.consulting.ConditionHandler
/information-center/consulting/counsel.do=mvc.command.consulting.CounselHandler
/information-center/consulting/process.do=mvc.command.consulting.ProcessHandler
/information-center/consulting/faq.do=mvc.command.consulting.FaqHandler
/information-center/consulting/store-list.do=mvc.command.consulting.ListHandler
/information-center/consulting/store-view.do=mvc.command.consulting.ViewHandler
/information-center/store-offer/offer.do=mvc.command.store_offer.StoreOfferHandler
/information-center/store-offer/register.do=mvc.command.store_offer.RegisterHandler

# /board/list.do=mvc.command.ListHandler
/menu/list.do=mvc.command.menu.ListHandler
/views/play/event/list.do=mvc.command.event.ListHandler
/views/play/event/view.do=mvc.command.event.ViewHandler

/views/play/plaza/list.do=mvc.command.plaza.ListHandler
/views/play/plaza/view.do=mvc.command.plaza.ViewHandler
/views/play/plaza/consulting.do=mvc.command.plaza.ConsultingHandler
/api/store-address.do=mvc.command.api.StoreAddressProxyHandler
/views/play/plaza/new.do=mvc.command.plaza.NewHandler
/views/play/plaza/collabo.do=mvc.command.plaza.CollaboHandler
/views/play/recipe/list.do=mvc.command.recipe.ListHandler
/views/play/recipe/view.do=mvc.command.recipe.ViewHandler
/views/play/myflavor/list.do=mvc.command.myflavor.ListHandler
/views/play/myflavor/register.do=mvc.command.myflavor.RegisterHandler
/views/play/myflavor/image.do=mvc.command.myflavor.MyFlavorImageHandler





/store/catering-order.do=mvc.command.store.CateringOrderHandler

/admin/main.do=mvc.command.admin.MainHandler


