# requestURI=CommandHandler Mapping

/menu/list.do=mvc.command.menu.ListHandler
/story/be-better.do=mvc.command.story.CampaignInfoHandler
/story/history.do=mvc.command.story.HistoryListHandler
/story/story.do=mvc.command.story.StoryListHandler
/login/login.do=mvc.command.login.LoginHandler
/login/logout.do=mvc.command.login.LogoutHandler
/join/join.do=mvc.command.join.JoinHandler
/login/findId.do=mvc.command.login.FindIdHandler
/login/findIdPhone.do=mvc.command.login.FindIdPhoneHandler
/login/findIdEmail.do=mvc.command.login.FindIdEmailHandler
/login/pwdResetRequest.do=mvc.command.login.PwdResetRequestHandler
/join/idCheck.do=mvc.command.join.IdCheckHandler
/join/nicknameCheck.do=mvc.command.join.NickNameCheckHandler
/join/emailCheck.do=mvc.command.join.EmailCheckHandler
/join/phoneSendCode.do=mvc.command.join.PhoneSendCodeHandler
/join/phoneVerifyCode.do=mvc.command.join.PhoneVerifyCodeHandler
/mypage/mypage.do=mvc.command.mypage.MyPageViewHandler
/mypage/profileEditForm.do=mvc.command.mypage.ProfileEditFormHandler
/mypage/profileEditSubmit.do=mvc.command.mypage.ProfileEditSubmitHandler
/mypage/nicknameCheck.do=mvc.command.mypage.NickNameCheckHandler
/mypage/emailCheck.do=mvc.command.mypage.EmailCheckHandler
/mypage/phoneSendCode.do=mvc.command.mypage.PhoneSendCodeHandler
/mypage/phoneVerifyCode.do=mvc.command.mypage.PhoneVerifyCodeHandler
#/mypage/pwdChange.do=mvc.command.mypage.PwdChangeHandler